version: '2.1'

services:
  darrenbayliss-dev2:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/labs/darrenbayliss-dev2
    ports:
      - $SERVER_PORT:$SERVER_PORT
